const TOGGLE_WATCH = 'TOGGLE_WATCH';
const RESET_WATCH = 'RESET_WATCH';
const GET_TIME = 'GET_TIME';
const LOCATION_CHANGED = 'LOCATION_CHANGED';
const TICK = 'TICK';
const SHOW_MODAL = 'SHOW_MODAL';
const HIDE_MODAL = 'HIDE_MODAL';
const ACCELERATION_CHANGED = 'ACCELERATION_CHANGED';

export {
    TOGGLE_WATCH,
    RESET_WATCH,
    LOCATION_CHANGED,
    TICK,
    SHOW_MODAL,
    HIDE_MODAL,
    ACCELERATION_CHANGED
};